// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class ContactInfo;
@class ContactInfoBuilder;
@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupNickSerialInfo;
@class GroupNickSerialInfoBuilder;
@class GroupUserInfo;
@class GroupUserInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IMGroupChangeMemberNotify;
@class IMGroupChangeMemberNotifyBuilder;
@class IMGroupChangeMemberReq;
@class IMGroupChangeMemberReqBuilder;
@class IMGroupChangeMemberRsp;
@class IMGroupChangeMemberRspBuilder;
@class IMGroupCreateReq;
@class IMGroupCreateReqBuilder;
@class IMGroupCreateRsp;
@class IMGroupCreateRspBuilder;
@class IMGroupCreatorChangeReq;
@class IMGroupCreatorChangeReqBuilder;
@class IMGroupCreatorChangeRsp;
@class IMGroupCreatorChangeRspBuilder;
@class IMGroupInfoChangeNotify;
@class IMGroupInfoChangeNotifyBuilder;
@class IMGroupInfoListReq;
@class IMGroupInfoListReqBuilder;
@class IMGroupInfoListRsp;
@class IMGroupInfoListRspBuilder;
@class IMGroupNameChangeReq;
@class IMGroupNameChangeReqBuilder;
@class IMGroupNameChangeRsp;
@class IMGroupNameChangeRspBuilder;
@class IMGroupNickSerial;
@class IMGroupNickSerialBuilder;
@class IMGroupShieldReq;
@class IMGroupShieldReqBuilder;
@class IMGroupShieldRsp;
@class IMGroupShieldRspBuilder;
@class IMNormalGroupListReq;
@class IMNormalGroupListReqBuilder;
@class IMNormalGroupListRsp;
@class IMNormalGroupListRspBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class SubscribeAttentionInfo;
@class SubscribeAttentionInfoBuilder;
@class SubscribeInfo;
@class SubscribeInfoBuilder;
@class SubsribeMsgIdInfo;
@class SubsribeMsgIdInfoBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;
@class UserUpdateInfo;
@class UserUpdateInfoBuilder;
@class VerifyInfo;
@class VerifyInfoBuilder;



@interface ImgroupRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMNormalGroupListReq_user_id @"userId"
#define IMNormalGroupListReq_attach_data @"attachData"
@interface IMNormalGroupListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  UInt64 userId;
  NSData* attachData;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMNormalGroupListReqBuilder*) builder;
+ (IMNormalGroupListReqBuilder*) builder;
+ (IMNormalGroupListReqBuilder*) builderWithPrototype:(IMNormalGroupListReq*) prototype;
- (IMNormalGroupListReqBuilder*) toBuilder;

+ (IMNormalGroupListReq*) parseFromData:(NSData*) data;
+ (IMNormalGroupListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMNormalGroupListReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMNormalGroupListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMNormalGroupListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMNormalGroupListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMNormalGroupListReqBuilder : PBGeneratedMessageBuilder {
@private
  IMNormalGroupListReq* resultImnormalGroupListReq;
}

- (IMNormalGroupListReq*) defaultInstance;

- (IMNormalGroupListReqBuilder*) clear;
- (IMNormalGroupListReqBuilder*) clone;

- (IMNormalGroupListReq*) build;
- (IMNormalGroupListReq*) buildPartial;

- (IMNormalGroupListReqBuilder*) mergeFrom:(IMNormalGroupListReq*) other;
- (IMNormalGroupListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMNormalGroupListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMNormalGroupListReqBuilder*) setUserId:(UInt64) value;
- (IMNormalGroupListReqBuilder*) clearUserId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMNormalGroupListReqBuilder*) setAttachData:(NSData*) value;
- (IMNormalGroupListReqBuilder*) clearAttachData;
@end

#define IMNormalGroupListRsp_user_id @"userId"
#define IMNormalGroupListRsp_group_version_list @"groupVersionList"
#define IMNormalGroupListRsp_attach_data @"attachData"
@interface IMNormalGroupListRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  UInt64 userId;
  NSData* attachData;
  NSMutableArray * groupVersionListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly, strong) NSArray * groupVersionList;
@property (readonly, strong) NSData* attachData;
- (GroupVersionInfo*)groupVersionListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMNormalGroupListRspBuilder*) builder;
+ (IMNormalGroupListRspBuilder*) builder;
+ (IMNormalGroupListRspBuilder*) builderWithPrototype:(IMNormalGroupListRsp*) prototype;
- (IMNormalGroupListRspBuilder*) toBuilder;

+ (IMNormalGroupListRsp*) parseFromData:(NSData*) data;
+ (IMNormalGroupListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMNormalGroupListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMNormalGroupListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMNormalGroupListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMNormalGroupListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMNormalGroupListRspBuilder : PBGeneratedMessageBuilder {
@private
  IMNormalGroupListRsp* resultImnormalGroupListRsp;
}

- (IMNormalGroupListRsp*) defaultInstance;

- (IMNormalGroupListRspBuilder*) clear;
- (IMNormalGroupListRspBuilder*) clone;

- (IMNormalGroupListRsp*) build;
- (IMNormalGroupListRsp*) buildPartial;

- (IMNormalGroupListRspBuilder*) mergeFrom:(IMNormalGroupListRsp*) other;
- (IMNormalGroupListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMNormalGroupListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMNormalGroupListRspBuilder*) setUserId:(UInt64) value;
- (IMNormalGroupListRspBuilder*) clearUserId;

- (NSMutableArray *)groupVersionList;
- (GroupVersionInfo*)groupVersionListAtIndex:(NSUInteger)index;
- (IMNormalGroupListRspBuilder *)addGroupVersionList:(GroupVersionInfo*)value;
- (IMNormalGroupListRspBuilder *)setGroupVersionListArray:(NSArray *)array;
- (IMNormalGroupListRspBuilder *)clearGroupVersionList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMNormalGroupListRspBuilder*) setAttachData:(NSData*) value;
- (IMNormalGroupListRspBuilder*) clearAttachData;
@end

#define IMGroupInfoListReq_user_id @"userId"
#define IMGroupInfoListReq_group_version_list @"groupVersionList"
#define IMGroupInfoListReq_attach_data @"attachData"
@interface IMGroupInfoListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  UInt64 userId;
  NSData* attachData;
  NSMutableArray * groupVersionListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly, strong) NSArray * groupVersionList;
@property (readonly, strong) NSData* attachData;
- (GroupVersionInfo*)groupVersionListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupInfoListReqBuilder*) builder;
+ (IMGroupInfoListReqBuilder*) builder;
+ (IMGroupInfoListReqBuilder*) builderWithPrototype:(IMGroupInfoListReq*) prototype;
- (IMGroupInfoListReqBuilder*) toBuilder;

+ (IMGroupInfoListReq*) parseFromData:(NSData*) data;
+ (IMGroupInfoListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoListReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupInfoListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupInfoListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupInfoListReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupInfoListReq* resultImgroupInfoListReq;
}

- (IMGroupInfoListReq*) defaultInstance;

- (IMGroupInfoListReqBuilder*) clear;
- (IMGroupInfoListReqBuilder*) clone;

- (IMGroupInfoListReq*) build;
- (IMGroupInfoListReq*) buildPartial;

- (IMGroupInfoListReqBuilder*) mergeFrom:(IMGroupInfoListReq*) other;
- (IMGroupInfoListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupInfoListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupInfoListReqBuilder*) setUserId:(UInt64) value;
- (IMGroupInfoListReqBuilder*) clearUserId;

- (NSMutableArray *)groupVersionList;
- (GroupVersionInfo*)groupVersionListAtIndex:(NSUInteger)index;
- (IMGroupInfoListReqBuilder *)addGroupVersionList:(GroupVersionInfo*)value;
- (IMGroupInfoListReqBuilder *)setGroupVersionListArray:(NSArray *)array;
- (IMGroupInfoListReqBuilder *)clearGroupVersionList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupInfoListReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupInfoListReqBuilder*) clearAttachData;
@end

#define IMGroupInfoListRsp_user_id @"userId"
#define IMGroupInfoListRsp_group_info_list @"groupInfoList"
#define IMGroupInfoListRsp_attach_data @"attachData"
@interface IMGroupInfoListRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  UInt64 userId;
  NSData* attachData;
  NSMutableArray * groupInfoListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly, strong) NSArray * groupInfoList;
@property (readonly, strong) NSData* attachData;
- (GroupInfo*)groupInfoListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupInfoListRspBuilder*) builder;
+ (IMGroupInfoListRspBuilder*) builder;
+ (IMGroupInfoListRspBuilder*) builderWithPrototype:(IMGroupInfoListRsp*) prototype;
- (IMGroupInfoListRspBuilder*) toBuilder;

+ (IMGroupInfoListRsp*) parseFromData:(NSData*) data;
+ (IMGroupInfoListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupInfoListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupInfoListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupInfoListRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupInfoListRsp* resultImgroupInfoListRsp;
}

- (IMGroupInfoListRsp*) defaultInstance;

- (IMGroupInfoListRspBuilder*) clear;
- (IMGroupInfoListRspBuilder*) clone;

- (IMGroupInfoListRsp*) build;
- (IMGroupInfoListRsp*) buildPartial;

- (IMGroupInfoListRspBuilder*) mergeFrom:(IMGroupInfoListRsp*) other;
- (IMGroupInfoListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupInfoListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupInfoListRspBuilder*) setUserId:(UInt64) value;
- (IMGroupInfoListRspBuilder*) clearUserId;

- (NSMutableArray *)groupInfoList;
- (GroupInfo*)groupInfoListAtIndex:(NSUInteger)index;
- (IMGroupInfoListRspBuilder *)addGroupInfoList:(GroupInfo*)value;
- (IMGroupInfoListRspBuilder *)setGroupInfoListArray:(NSArray *)array;
- (IMGroupInfoListRspBuilder *)clearGroupInfoList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupInfoListRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupInfoListRspBuilder*) clearAttachData;
@end

#define IMGroupCreateReq_user_id @"userId"
#define IMGroupCreateReq_group_type @"groupType"
#define IMGroupCreateReq_group_name @"groupName"
#define IMGroupCreateReq_group_avatar @"groupAvatar"
#define IMGroupCreateReq_member_id_list @"memberIdList"
#define IMGroupCreateReq_attach_data @"attachData"
@interface IMGroupCreateReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasAttachData_:1;
  BOOL hasGroupType_:1;
  UInt64 userId;
  NSString* groupName;
  NSString* groupAvatar;
  NSData* attachData;
  GroupType groupType;
  PBAppendableArray * memberIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupType;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) GroupType groupType;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* groupAvatar;
@property (readonly, strong) PBArray * memberIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)memberIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupCreateReqBuilder*) builder;
+ (IMGroupCreateReqBuilder*) builder;
+ (IMGroupCreateReqBuilder*) builderWithPrototype:(IMGroupCreateReq*) prototype;
- (IMGroupCreateReqBuilder*) toBuilder;

+ (IMGroupCreateReq*) parseFromData:(NSData*) data;
+ (IMGroupCreateReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreateReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupCreateReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupCreateReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupCreateReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupCreateReq* resultImgroupCreateReq;
}

- (IMGroupCreateReq*) defaultInstance;

- (IMGroupCreateReqBuilder*) clear;
- (IMGroupCreateReqBuilder*) clone;

- (IMGroupCreateReq*) build;
- (IMGroupCreateReq*) buildPartial;

- (IMGroupCreateReqBuilder*) mergeFrom:(IMGroupCreateReq*) other;
- (IMGroupCreateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupCreateReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupCreateReqBuilder*) setUserId:(UInt64) value;
- (IMGroupCreateReqBuilder*) clearUserId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (IMGroupCreateReqBuilder*) setGroupType:(GroupType) value;
- (IMGroupCreateReqBuilder*) clearGroupType;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (IMGroupCreateReqBuilder*) setGroupName:(NSString*) value;
- (IMGroupCreateReqBuilder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (IMGroupCreateReqBuilder*) setGroupAvatar:(NSString*) value;
- (IMGroupCreateReqBuilder*) clearGroupAvatar;

- (PBAppendableArray *)memberIdList;
- (UInt64)memberIdListAtIndex:(NSUInteger)index;
- (IMGroupCreateReqBuilder *)addMemberIdList:(UInt64)value;
- (IMGroupCreateReqBuilder *)setMemberIdListArray:(NSArray *)array;
- (IMGroupCreateReqBuilder *)setMemberIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupCreateReqBuilder *)clearMemberIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupCreateReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupCreateReqBuilder*) clearAttachData;
@end

#define IMGroupCreateRsp_user_id @"userId"
#define IMGroupCreateRsp_result_code @"resultCode"
#define IMGroupCreateRsp_group_id @"groupId"
#define IMGroupCreateRsp_group_name @"groupName"
#define IMGroupCreateRsp_user_id_list @"userIdList"
#define IMGroupCreateRsp_attach_data @"attachData"
@interface IMGroupCreateRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  UInt64 userId;
  UInt64 groupId;
  NSString* groupName;
  NSData* attachData;
  UInt32 resultCode;
  PBAppendableArray * userIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasResultCode;
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt32 resultCode;
@property (readonly) UInt64 groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) PBArray * userIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)userIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupCreateRspBuilder*) builder;
+ (IMGroupCreateRspBuilder*) builder;
+ (IMGroupCreateRspBuilder*) builderWithPrototype:(IMGroupCreateRsp*) prototype;
- (IMGroupCreateRspBuilder*) toBuilder;

+ (IMGroupCreateRsp*) parseFromData:(NSData*) data;
+ (IMGroupCreateRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreateRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupCreateRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreateRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupCreateRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupCreateRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupCreateRsp* resultImgroupCreateRsp;
}

- (IMGroupCreateRsp*) defaultInstance;

- (IMGroupCreateRspBuilder*) clear;
- (IMGroupCreateRspBuilder*) clone;

- (IMGroupCreateRsp*) build;
- (IMGroupCreateRsp*) buildPartial;

- (IMGroupCreateRspBuilder*) mergeFrom:(IMGroupCreateRsp*) other;
- (IMGroupCreateRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupCreateRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupCreateRspBuilder*) setUserId:(UInt64) value;
- (IMGroupCreateRspBuilder*) clearUserId;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMGroupCreateRspBuilder*) setResultCode:(UInt32) value;
- (IMGroupCreateRspBuilder*) clearResultCode;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupCreateRspBuilder*) setGroupId:(UInt64) value;
- (IMGroupCreateRspBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (IMGroupCreateRspBuilder*) setGroupName:(NSString*) value;
- (IMGroupCreateRspBuilder*) clearGroupName;

- (PBAppendableArray *)userIdList;
- (UInt64)userIdListAtIndex:(NSUInteger)index;
- (IMGroupCreateRspBuilder *)addUserIdList:(UInt64)value;
- (IMGroupCreateRspBuilder *)setUserIdListArray:(NSArray *)array;
- (IMGroupCreateRspBuilder *)setUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupCreateRspBuilder *)clearUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupCreateRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupCreateRspBuilder*) clearAttachData;
@end

#define IMGroupChangeMemberReq_user_id @"userId"
#define IMGroupChangeMemberReq_change_type @"changeType"
#define IMGroupChangeMemberReq_group_id @"groupId"
#define IMGroupChangeMemberReq_member_id_list @"memberIdList"
#define IMGroupChangeMemberReq_attach_data @"attachData"
@interface IMGroupChangeMemberReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasAttachData_:1;
  BOOL hasChangeType_:1;
  UInt64 userId;
  UInt64 groupId;
  NSData* attachData;
  GroupModifyType changeType;
  PBAppendableArray * memberIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasChangeType;
- (BOOL) hasGroupId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) GroupModifyType changeType;
@property (readonly) UInt64 groupId;
@property (readonly, strong) PBArray * memberIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)memberIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupChangeMemberReqBuilder*) builder;
+ (IMGroupChangeMemberReqBuilder*) builder;
+ (IMGroupChangeMemberReqBuilder*) builderWithPrototype:(IMGroupChangeMemberReq*) prototype;
- (IMGroupChangeMemberReqBuilder*) toBuilder;

+ (IMGroupChangeMemberReq*) parseFromData:(NSData*) data;
+ (IMGroupChangeMemberReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupChangeMemberReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupChangeMemberReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupChangeMemberReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupChangeMemberReq* resultImgroupChangeMemberReq;
}

- (IMGroupChangeMemberReq*) defaultInstance;

- (IMGroupChangeMemberReqBuilder*) clear;
- (IMGroupChangeMemberReqBuilder*) clone;

- (IMGroupChangeMemberReq*) build;
- (IMGroupChangeMemberReq*) buildPartial;

- (IMGroupChangeMemberReqBuilder*) mergeFrom:(IMGroupChangeMemberReq*) other;
- (IMGroupChangeMemberReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupChangeMemberReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupChangeMemberReqBuilder*) setUserId:(UInt64) value;
- (IMGroupChangeMemberReqBuilder*) clearUserId;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupChangeMemberReqBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupChangeMemberReqBuilder*) clearChangeType;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupChangeMemberReqBuilder*) setGroupId:(UInt64) value;
- (IMGroupChangeMemberReqBuilder*) clearGroupId;

- (PBAppendableArray *)memberIdList;
- (UInt64)memberIdListAtIndex:(NSUInteger)index;
- (IMGroupChangeMemberReqBuilder *)addMemberIdList:(UInt64)value;
- (IMGroupChangeMemberReqBuilder *)setMemberIdListArray:(NSArray *)array;
- (IMGroupChangeMemberReqBuilder *)setMemberIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupChangeMemberReqBuilder *)clearMemberIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupChangeMemberReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupChangeMemberReqBuilder*) clearAttachData;
@end

#define IMGroupChangeMemberRsp_user_id @"userId"
#define IMGroupChangeMemberRsp_change_type @"changeType"
#define IMGroupChangeMemberRsp_result_code @"resultCode"
#define IMGroupChangeMemberRsp_group_id @"groupId"
#define IMGroupChangeMemberRsp_cur_user_id_list @"curUserIdList"
#define IMGroupChangeMemberRsp_chg_user_id_list @"chgUserIdList"
#define IMGroupChangeMemberRsp_attach_data @"attachData"
@interface IMGroupChangeMemberRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  BOOL hasChangeType_:1;
  UInt64 userId;
  UInt64 groupId;
  NSData* attachData;
  UInt32 resultCode;
  GroupModifyType changeType;
  PBAppendableArray * curUserIdListArray;
  PBAppendableArray * chgUserIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasChangeType;
- (BOOL) hasResultCode;
- (BOOL) hasGroupId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) GroupModifyType changeType;
@property (readonly) UInt32 resultCode;
@property (readonly) UInt64 groupId;
@property (readonly, strong) PBArray * curUserIdList;
@property (readonly, strong) PBArray * chgUserIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (UInt64)chgUserIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupChangeMemberRspBuilder*) builder;
+ (IMGroupChangeMemberRspBuilder*) builder;
+ (IMGroupChangeMemberRspBuilder*) builderWithPrototype:(IMGroupChangeMemberRsp*) prototype;
- (IMGroupChangeMemberRspBuilder*) toBuilder;

+ (IMGroupChangeMemberRsp*) parseFromData:(NSData*) data;
+ (IMGroupChangeMemberRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupChangeMemberRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupChangeMemberRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupChangeMemberRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupChangeMemberRsp* resultImgroupChangeMemberRsp;
}

- (IMGroupChangeMemberRsp*) defaultInstance;

- (IMGroupChangeMemberRspBuilder*) clear;
- (IMGroupChangeMemberRspBuilder*) clone;

- (IMGroupChangeMemberRsp*) build;
- (IMGroupChangeMemberRsp*) buildPartial;

- (IMGroupChangeMemberRspBuilder*) mergeFrom:(IMGroupChangeMemberRsp*) other;
- (IMGroupChangeMemberRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupChangeMemberRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupChangeMemberRspBuilder*) setUserId:(UInt64) value;
- (IMGroupChangeMemberRspBuilder*) clearUserId;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupChangeMemberRspBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupChangeMemberRspBuilder*) clearChangeType;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMGroupChangeMemberRspBuilder*) setResultCode:(UInt32) value;
- (IMGroupChangeMemberRspBuilder*) clearResultCode;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupChangeMemberRspBuilder*) setGroupId:(UInt64) value;
- (IMGroupChangeMemberRspBuilder*) clearGroupId;

- (PBAppendableArray *)curUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (IMGroupChangeMemberRspBuilder *)addCurUserIdList:(UInt64)value;
- (IMGroupChangeMemberRspBuilder *)setCurUserIdListArray:(NSArray *)array;
- (IMGroupChangeMemberRspBuilder *)setCurUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupChangeMemberRspBuilder *)clearCurUserIdList;

- (PBAppendableArray *)chgUserIdList;
- (UInt64)chgUserIdListAtIndex:(NSUInteger)index;
- (IMGroupChangeMemberRspBuilder *)addChgUserIdList:(UInt64)value;
- (IMGroupChangeMemberRspBuilder *)setChgUserIdListArray:(NSArray *)array;
- (IMGroupChangeMemberRspBuilder *)setChgUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupChangeMemberRspBuilder *)clearChgUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupChangeMemberRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupChangeMemberRspBuilder*) clearAttachData;
@end

#define IMGroupShieldReq_user_id @"userId"
#define IMGroupShieldReq_group_id @"groupId"
#define IMGroupShieldReq_shield_status @"shieldStatus"
#define IMGroupShieldReq_attach_data @"attachData"
@interface IMGroupShieldReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasAttachData_:1;
  BOOL hasShieldStatus_:1;
  UInt64 userId;
  UInt64 groupId;
  NSData* attachData;
  UInt32 shieldStatus;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasShieldStatus;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 groupId;
@property (readonly) UInt32 shieldStatus;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupShieldReqBuilder*) builder;
+ (IMGroupShieldReqBuilder*) builder;
+ (IMGroupShieldReqBuilder*) builderWithPrototype:(IMGroupShieldReq*) prototype;
- (IMGroupShieldReqBuilder*) toBuilder;

+ (IMGroupShieldReq*) parseFromData:(NSData*) data;
+ (IMGroupShieldReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupShieldReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupShieldReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupShieldReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupShieldReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupShieldReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupShieldReq* resultImgroupShieldReq;
}

- (IMGroupShieldReq*) defaultInstance;

- (IMGroupShieldReqBuilder*) clear;
- (IMGroupShieldReqBuilder*) clone;

- (IMGroupShieldReq*) build;
- (IMGroupShieldReq*) buildPartial;

- (IMGroupShieldReqBuilder*) mergeFrom:(IMGroupShieldReq*) other;
- (IMGroupShieldReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupShieldReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupShieldReqBuilder*) setUserId:(UInt64) value;
- (IMGroupShieldReqBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupShieldReqBuilder*) setGroupId:(UInt64) value;
- (IMGroupShieldReqBuilder*) clearGroupId;

- (BOOL) hasShieldStatus;
- (UInt32) shieldStatus;
- (IMGroupShieldReqBuilder*) setShieldStatus:(UInt32) value;
- (IMGroupShieldReqBuilder*) clearShieldStatus;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupShieldReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupShieldReqBuilder*) clearAttachData;
@end

#define IMGroupShieldRsp_user_id @"userId"
#define IMGroupShieldRsp_group_id @"groupId"
#define IMGroupShieldRsp_result_code @"resultCode"
#define IMGroupShieldRsp_attach_data @"attachData"
@interface IMGroupShieldRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  UInt64 userId;
  UInt64 groupId;
  NSData* attachData;
  UInt32 resultCode;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasResultCode;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 groupId;
@property (readonly) UInt32 resultCode;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupShieldRspBuilder*) builder;
+ (IMGroupShieldRspBuilder*) builder;
+ (IMGroupShieldRspBuilder*) builderWithPrototype:(IMGroupShieldRsp*) prototype;
- (IMGroupShieldRspBuilder*) toBuilder;

+ (IMGroupShieldRsp*) parseFromData:(NSData*) data;
+ (IMGroupShieldRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupShieldRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupShieldRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupShieldRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupShieldRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupShieldRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupShieldRsp* resultImgroupShieldRsp;
}

- (IMGroupShieldRsp*) defaultInstance;

- (IMGroupShieldRspBuilder*) clear;
- (IMGroupShieldRspBuilder*) clone;

- (IMGroupShieldRsp*) build;
- (IMGroupShieldRsp*) buildPartial;

- (IMGroupShieldRspBuilder*) mergeFrom:(IMGroupShieldRsp*) other;
- (IMGroupShieldRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupShieldRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupShieldRspBuilder*) setUserId:(UInt64) value;
- (IMGroupShieldRspBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupShieldRspBuilder*) setGroupId:(UInt64) value;
- (IMGroupShieldRspBuilder*) clearGroupId;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMGroupShieldRspBuilder*) setResultCode:(UInt32) value;
- (IMGroupShieldRspBuilder*) clearResultCode;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupShieldRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupShieldRspBuilder*) clearAttachData;
@end

#define IMGroupChangeMemberNotify_user_id @"userId"
#define IMGroupChangeMemberNotify_change_type @"changeType"
#define IMGroupChangeMemberNotify_group_id @"groupId"
#define IMGroupChangeMemberNotify_cur_user_id_list @"curUserIdList"
#define IMGroupChangeMemberNotify_chg_user_id_list @"chgUserIdList"
@interface IMGroupChangeMemberNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasChangeType_:1;
  UInt64 userId;
  UInt64 groupId;
  GroupModifyType changeType;
  PBAppendableArray * curUserIdListArray;
  PBAppendableArray * chgUserIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasChangeType;
- (BOOL) hasGroupId;
@property (readonly) UInt64 userId;
@property (readonly) GroupModifyType changeType;
@property (readonly) UInt64 groupId;
@property (readonly, strong) PBArray * curUserIdList;
@property (readonly, strong) PBArray * chgUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (UInt64)chgUserIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupChangeMemberNotifyBuilder*) builder;
+ (IMGroupChangeMemberNotifyBuilder*) builder;
+ (IMGroupChangeMemberNotifyBuilder*) builderWithPrototype:(IMGroupChangeMemberNotify*) prototype;
- (IMGroupChangeMemberNotifyBuilder*) toBuilder;

+ (IMGroupChangeMemberNotify*) parseFromData:(NSData*) data;
+ (IMGroupChangeMemberNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupChangeMemberNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupChangeMemberNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupChangeMemberNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupChangeMemberNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupChangeMemberNotify* resultImgroupChangeMemberNotify;
}

- (IMGroupChangeMemberNotify*) defaultInstance;

- (IMGroupChangeMemberNotifyBuilder*) clear;
- (IMGroupChangeMemberNotifyBuilder*) clone;

- (IMGroupChangeMemberNotify*) build;
- (IMGroupChangeMemberNotify*) buildPartial;

- (IMGroupChangeMemberNotifyBuilder*) mergeFrom:(IMGroupChangeMemberNotify*) other;
- (IMGroupChangeMemberNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupChangeMemberNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupChangeMemberNotifyBuilder*) setUserId:(UInt64) value;
- (IMGroupChangeMemberNotifyBuilder*) clearUserId;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupChangeMemberNotifyBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupChangeMemberNotifyBuilder*) clearChangeType;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupChangeMemberNotifyBuilder*) setGroupId:(UInt64) value;
- (IMGroupChangeMemberNotifyBuilder*) clearGroupId;

- (PBAppendableArray *)curUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (IMGroupChangeMemberNotifyBuilder *)addCurUserIdList:(UInt64)value;
- (IMGroupChangeMemberNotifyBuilder *)setCurUserIdListArray:(NSArray *)array;
- (IMGroupChangeMemberNotifyBuilder *)setCurUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupChangeMemberNotifyBuilder *)clearCurUserIdList;

- (PBAppendableArray *)chgUserIdList;
- (UInt64)chgUserIdListAtIndex:(NSUInteger)index;
- (IMGroupChangeMemberNotifyBuilder *)addChgUserIdList:(UInt64)value;
- (IMGroupChangeMemberNotifyBuilder *)setChgUserIdListArray:(NSArray *)array;
- (IMGroupChangeMemberNotifyBuilder *)setChgUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupChangeMemberNotifyBuilder *)clearChgUserIdList;
@end

#define IMGroupNameChangeReq_user_id @"userId"
#define IMGroupNameChangeReq_group_id @"groupId"
#define IMGroupNameChangeReq_change_type @"changeType"
#define IMGroupNameChangeReq_value @"value"
#define IMGroupNameChangeReq_attach_data @"attachData"
@interface IMGroupNameChangeReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasValue_:1;
  BOOL hasAttachData_:1;
  BOOL hasChangeType_:1;
  UInt64 userId;
  UInt64 groupId;
  NSString* value;
  NSData* attachData;
  GroupModifyType changeType;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasChangeType;
- (BOOL) hasValue;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 groupId;
@property (readonly) GroupModifyType changeType;
@property (readonly, strong) NSString* value;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupNameChangeReqBuilder*) builder;
+ (IMGroupNameChangeReqBuilder*) builder;
+ (IMGroupNameChangeReqBuilder*) builderWithPrototype:(IMGroupNameChangeReq*) prototype;
- (IMGroupNameChangeReqBuilder*) toBuilder;

+ (IMGroupNameChangeReq*) parseFromData:(NSData*) data;
+ (IMGroupNameChangeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNameChangeReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupNameChangeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNameChangeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupNameChangeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupNameChangeReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupNameChangeReq* resultImgroupNameChangeReq;
}

- (IMGroupNameChangeReq*) defaultInstance;

- (IMGroupNameChangeReqBuilder*) clear;
- (IMGroupNameChangeReqBuilder*) clone;

- (IMGroupNameChangeReq*) build;
- (IMGroupNameChangeReq*) buildPartial;

- (IMGroupNameChangeReqBuilder*) mergeFrom:(IMGroupNameChangeReq*) other;
- (IMGroupNameChangeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupNameChangeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupNameChangeReqBuilder*) setUserId:(UInt64) value;
- (IMGroupNameChangeReqBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupNameChangeReqBuilder*) setGroupId:(UInt64) value;
- (IMGroupNameChangeReqBuilder*) clearGroupId;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupNameChangeReqBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupNameChangeReqBuilder*) clearChangeType;

- (BOOL) hasValue;
- (NSString*) value;
- (IMGroupNameChangeReqBuilder*) setValue:(NSString*) value;
- (IMGroupNameChangeReqBuilder*) clearValue;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupNameChangeReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupNameChangeReqBuilder*) clearAttachData;
@end

#define IMGroupNameChangeRsp_user_id @"userId"
#define IMGroupNameChangeRsp_group_id @"groupId"
#define IMGroupNameChangeRsp_change_type @"changeType"
#define IMGroupNameChangeRsp_code @"code"
#define IMGroupNameChangeRsp_value @"value"
#define IMGroupNameChangeRsp_cur_user_id_list @"curUserIdList"
#define IMGroupNameChangeRsp_attach_data @"attachData"
@interface IMGroupNameChangeRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasValue_:1;
  BOOL hasAttachData_:1;
  BOOL hasChangeType_:1;
  BOOL hasCode_:1;
  UInt64 userId;
  UInt64 groupId;
  NSString* value;
  NSData* attachData;
  GroupModifyType changeType;
  ContactModifyRetCode code;
  PBAppendableArray * curUserIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasChangeType;
- (BOOL) hasCode;
- (BOOL) hasValue;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 groupId;
@property (readonly) GroupModifyType changeType;
@property (readonly) ContactModifyRetCode code;
@property (readonly, strong) NSString* value;
@property (readonly, strong) PBArray * curUserIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupNameChangeRspBuilder*) builder;
+ (IMGroupNameChangeRspBuilder*) builder;
+ (IMGroupNameChangeRspBuilder*) builderWithPrototype:(IMGroupNameChangeRsp*) prototype;
- (IMGroupNameChangeRspBuilder*) toBuilder;

+ (IMGroupNameChangeRsp*) parseFromData:(NSData*) data;
+ (IMGroupNameChangeRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNameChangeRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupNameChangeRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNameChangeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupNameChangeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupNameChangeRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupNameChangeRsp* resultImgroupNameChangeRsp;
}

- (IMGroupNameChangeRsp*) defaultInstance;

- (IMGroupNameChangeRspBuilder*) clear;
- (IMGroupNameChangeRspBuilder*) clone;

- (IMGroupNameChangeRsp*) build;
- (IMGroupNameChangeRsp*) buildPartial;

- (IMGroupNameChangeRspBuilder*) mergeFrom:(IMGroupNameChangeRsp*) other;
- (IMGroupNameChangeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupNameChangeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupNameChangeRspBuilder*) setUserId:(UInt64) value;
- (IMGroupNameChangeRspBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupNameChangeRspBuilder*) setGroupId:(UInt64) value;
- (IMGroupNameChangeRspBuilder*) clearGroupId;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupNameChangeRspBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupNameChangeRspBuilder*) clearChangeType;

- (BOOL) hasCode;
- (ContactModifyRetCode) code;
- (IMGroupNameChangeRspBuilder*) setCode:(ContactModifyRetCode) value;
- (IMGroupNameChangeRspBuilder*) clearCode;

- (BOOL) hasValue;
- (NSString*) value;
- (IMGroupNameChangeRspBuilder*) setValue:(NSString*) value;
- (IMGroupNameChangeRspBuilder*) clearValue;

- (PBAppendableArray *)curUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (IMGroupNameChangeRspBuilder *)addCurUserIdList:(UInt64)value;
- (IMGroupNameChangeRspBuilder *)setCurUserIdListArray:(NSArray *)array;
- (IMGroupNameChangeRspBuilder *)setCurUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupNameChangeRspBuilder *)clearCurUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupNameChangeRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupNameChangeRspBuilder*) clearAttachData;
@end

#define IMGroupInfoChangeNotify_user_id @"userId"
#define IMGroupInfoChangeNotify_group_id @"groupId"
#define IMGroupInfoChangeNotify_cur_user_id_list @"curUserIdList"
#define IMGroupInfoChangeNotify_change_type @"changeType"
#define IMGroupInfoChangeNotify_value @"value"
@interface IMGroupInfoChangeNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasValue_:1;
  BOOL hasChangeType_:1;
  UInt64 userId;
  UInt64 groupId;
  NSString* value;
  GroupModifyType changeType;
  PBAppendableArray * curUserIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasChangeType;
- (BOOL) hasValue;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 groupId;
@property (readonly, strong) PBArray * curUserIdList;
@property (readonly) GroupModifyType changeType;
@property (readonly, strong) NSString* value;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupInfoChangeNotifyBuilder*) builder;
+ (IMGroupInfoChangeNotifyBuilder*) builder;
+ (IMGroupInfoChangeNotifyBuilder*) builderWithPrototype:(IMGroupInfoChangeNotify*) prototype;
- (IMGroupInfoChangeNotifyBuilder*) toBuilder;

+ (IMGroupInfoChangeNotify*) parseFromData:(NSData*) data;
+ (IMGroupInfoChangeNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoChangeNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupInfoChangeNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupInfoChangeNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupInfoChangeNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupInfoChangeNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupInfoChangeNotify* resultImgroupInfoChangeNotify;
}

- (IMGroupInfoChangeNotify*) defaultInstance;

- (IMGroupInfoChangeNotifyBuilder*) clear;
- (IMGroupInfoChangeNotifyBuilder*) clone;

- (IMGroupInfoChangeNotify*) build;
- (IMGroupInfoChangeNotify*) buildPartial;

- (IMGroupInfoChangeNotifyBuilder*) mergeFrom:(IMGroupInfoChangeNotify*) other;
- (IMGroupInfoChangeNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupInfoChangeNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGroupInfoChangeNotifyBuilder*) setUserId:(UInt64) value;
- (IMGroupInfoChangeNotifyBuilder*) clearUserId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupInfoChangeNotifyBuilder*) setGroupId:(UInt64) value;
- (IMGroupInfoChangeNotifyBuilder*) clearGroupId;

- (PBAppendableArray *)curUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (IMGroupInfoChangeNotifyBuilder *)addCurUserIdList:(UInt64)value;
- (IMGroupInfoChangeNotifyBuilder *)setCurUserIdListArray:(NSArray *)array;
- (IMGroupInfoChangeNotifyBuilder *)setCurUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGroupInfoChangeNotifyBuilder *)clearCurUserIdList;

- (BOOL) hasChangeType;
- (GroupModifyType) changeType;
- (IMGroupInfoChangeNotifyBuilder*) setChangeType:(GroupModifyType) value;
- (IMGroupInfoChangeNotifyBuilder*) clearChangeType;

- (BOOL) hasValue;
- (NSString*) value;
- (IMGroupInfoChangeNotifyBuilder*) setValue:(NSString*) value;
- (IMGroupInfoChangeNotifyBuilder*) clearValue;
@end

#define IMGroupCreatorChangeReq_creator_id @"creatorId"
#define IMGroupCreatorChangeReq_group_id @"groupId"
#define IMGroupCreatorChangeReq_attach_data @"attachData"
@interface IMGroupCreatorChangeReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCreatorId_:1;
  BOOL hasGroupId_:1;
  BOOL hasAttachData_:1;
  UInt64 creatorId;
  UInt64 groupId;
  NSData* attachData;
}
- (BOOL) hasCreatorId;
- (BOOL) hasGroupId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 creatorId;
@property (readonly) UInt64 groupId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupCreatorChangeReqBuilder*) builder;
+ (IMGroupCreatorChangeReqBuilder*) builder;
+ (IMGroupCreatorChangeReqBuilder*) builderWithPrototype:(IMGroupCreatorChangeReq*) prototype;
- (IMGroupCreatorChangeReqBuilder*) toBuilder;

+ (IMGroupCreatorChangeReq*) parseFromData:(NSData*) data;
+ (IMGroupCreatorChangeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreatorChangeReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupCreatorChangeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreatorChangeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupCreatorChangeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupCreatorChangeReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupCreatorChangeReq* resultImgroupCreatorChangeReq;
}

- (IMGroupCreatorChangeReq*) defaultInstance;

- (IMGroupCreatorChangeReqBuilder*) clear;
- (IMGroupCreatorChangeReqBuilder*) clone;

- (IMGroupCreatorChangeReq*) build;
- (IMGroupCreatorChangeReq*) buildPartial;

- (IMGroupCreatorChangeReqBuilder*) mergeFrom:(IMGroupCreatorChangeReq*) other;
- (IMGroupCreatorChangeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupCreatorChangeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCreatorId;
- (UInt64) creatorId;
- (IMGroupCreatorChangeReqBuilder*) setCreatorId:(UInt64) value;
- (IMGroupCreatorChangeReqBuilder*) clearCreatorId;

- (BOOL) hasGroupId;
- (UInt64) groupId;
- (IMGroupCreatorChangeReqBuilder*) setGroupId:(UInt64) value;
- (IMGroupCreatorChangeReqBuilder*) clearGroupId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupCreatorChangeReqBuilder*) setAttachData:(NSData*) value;
- (IMGroupCreatorChangeReqBuilder*) clearAttachData;
@end

#define IMGroupCreatorChangeRsp_result_code @"resultCode"
#define IMGroupCreatorChangeRsp_attach_data @"attachData"
@interface IMGroupCreatorChangeRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachData_:1;
  BOOL hasResultCode_:1;
  NSData* attachData;
  UInt32 resultCode;
}
- (BOOL) hasResultCode;
- (BOOL) hasAttachData;
@property (readonly) UInt32 resultCode;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupCreatorChangeRspBuilder*) builder;
+ (IMGroupCreatorChangeRspBuilder*) builder;
+ (IMGroupCreatorChangeRspBuilder*) builderWithPrototype:(IMGroupCreatorChangeRsp*) prototype;
- (IMGroupCreatorChangeRspBuilder*) toBuilder;

+ (IMGroupCreatorChangeRsp*) parseFromData:(NSData*) data;
+ (IMGroupCreatorChangeRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreatorChangeRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupCreatorChangeRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupCreatorChangeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupCreatorChangeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupCreatorChangeRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupCreatorChangeRsp* resultImgroupCreatorChangeRsp;
}

- (IMGroupCreatorChangeRsp*) defaultInstance;

- (IMGroupCreatorChangeRspBuilder*) clear;
- (IMGroupCreatorChangeRspBuilder*) clone;

- (IMGroupCreatorChangeRsp*) build;
- (IMGroupCreatorChangeRsp*) buildPartial;

- (IMGroupCreatorChangeRspBuilder*) mergeFrom:(IMGroupCreatorChangeRsp*) other;
- (IMGroupCreatorChangeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupCreatorChangeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResultCode;
- (UInt32) resultCode;
- (IMGroupCreatorChangeRspBuilder*) setResultCode:(UInt32) value;
- (IMGroupCreatorChangeRspBuilder*) clearResultCode;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGroupCreatorChangeRspBuilder*) setAttachData:(NSData*) value;
- (IMGroupCreatorChangeRspBuilder*) clearAttachData;
@end

#define IMGroupNickSerial_nicks @"nicks"
@interface IMGroupNickSerial : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * nicksArray;
}
@property (readonly, strong) NSArray * nicks;
- (GroupNickSerialInfo*)nicksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGroupNickSerialBuilder*) builder;
+ (IMGroupNickSerialBuilder*) builder;
+ (IMGroupNickSerialBuilder*) builderWithPrototype:(IMGroupNickSerial*) prototype;
- (IMGroupNickSerialBuilder*) toBuilder;

+ (IMGroupNickSerial*) parseFromData:(NSData*) data;
+ (IMGroupNickSerial*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNickSerial*) parseFromInputStream:(NSInputStream*) input;
+ (IMGroupNickSerial*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGroupNickSerial*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGroupNickSerial*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGroupNickSerialBuilder : PBGeneratedMessageBuilder {
@private
  IMGroupNickSerial* resultImgroupNickSerial;
}

- (IMGroupNickSerial*) defaultInstance;

- (IMGroupNickSerialBuilder*) clear;
- (IMGroupNickSerialBuilder*) clone;

- (IMGroupNickSerial*) build;
- (IMGroupNickSerial*) buildPartial;

- (IMGroupNickSerialBuilder*) mergeFrom:(IMGroupNickSerial*) other;
- (IMGroupNickSerialBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGroupNickSerialBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)nicks;
- (GroupNickSerialInfo*)nicksAtIndex:(NSUInteger)index;
- (IMGroupNickSerialBuilder *)addNicks:(GroupNickSerialInfo*)value;
- (IMGroupNickSerialBuilder *)setNicksArray:(NSArray *)array;
- (IMGroupNickSerialBuilder *)clearNicks;
@end


// @@protoc_insertion_point(global_scope)
