// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IMBaseDefine.pb.h"
// @@protoc_insertion_point(imports)

@class ContactInfo;
@class ContactInfoBuilder;
@class ContactSessionInfo;
@class ContactSessionInfoBuilder;
@class DepartInfo;
@class DepartInfoBuilder;
@class GroupInfo;
@class GroupInfoBuilder;
@class GroupNickSerialInfo;
@class GroupNickSerialInfoBuilder;
@class GroupUserInfo;
@class GroupUserInfoBuilder;
@class GroupVersionInfo;
@class GroupVersionInfoBuilder;
@class IMClientTimeReq;
@class IMClientTimeReqBuilder;
@class IMClientTimeRsp;
@class IMClientTimeRspBuilder;
@class IMGetLatestMsgIdReq;
@class IMGetLatestMsgIdReqBuilder;
@class IMGetLatestMsgIdRsp;
@class IMGetLatestMsgIdRspBuilder;
@class IMGetMsgByIdReq;
@class IMGetMsgByIdReqBuilder;
@class IMGetMsgByIdRsp;
@class IMGetMsgByIdRspBuilder;
@class IMGetMsgListReq;
@class IMGetMsgListReqBuilder;
@class IMGetMsgListRsp;
@class IMGetMsgListRspBuilder;
@class IMMsgData;
@class IMMsgDataAck;
@class IMMsgDataAckBuilder;
@class IMMsgDataBuilder;
@class IMMsgDataReadAck;
@class IMMsgDataReadAckBuilder;
@class IMMsgDataReadNotify;
@class IMMsgDataReadNotifyBuilder;
@class IMSubscribeHttpSendMessageRequest;
@class IMSubscribeHttpSendMessageRequestBuilder;
@class IMSubscribeHttpSendMessageRespone;
@class IMSubscribeHttpSendMessageResponeBuilder;
@class IMUnreadMsgCntReq;
@class IMUnreadMsgCntReqBuilder;
@class IMUnreadMsgCntRsp;
@class IMUnreadMsgCntRspBuilder;
@class IpAddr;
@class IpAddrBuilder;
@class MsgInfo;
@class MsgInfoBuilder;
@class OfflineFileInfo;
@class OfflineFileInfoBuilder;
@class PushResult;
@class PushResultBuilder;
@class ServerUserStat;
@class ServerUserStatBuilder;
@class ShieldStatus;
@class ShieldStatusBuilder;
@class SubscribeAttentionInfo;
@class SubscribeAttentionInfoBuilder;
@class SubscribeInfo;
@class SubscribeInfoBuilder;
@class SubsribeMsgIdInfo;
@class SubsribeMsgIdInfoBuilder;
@class UnreadInfo;
@class UnreadInfoBuilder;
@class UserInfo;
@class UserInfoBuilder;
@class UserStat;
@class UserStatBuilder;
@class UserTokenInfo;
@class UserTokenInfoBuilder;
@class UserUpdateInfo;
@class UserUpdateInfoBuilder;
@class VerifyInfo;
@class VerifyInfoBuilder;



@interface ImmessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMMsgData_from_user_id @"fromUserId"
#define IMMsgData_to_session_id @"toSessionId"
#define IMMsgData_msg_id @"msgId"
#define IMMsgData_create_time @"createTime"
#define IMMsgData_msg_type @"msgType"
#define IMMsgData_msg_data @"msgData"
#define IMMsgData_sender_lastet_updated @"senderLastetUpdated"
#define IMMsgData_cur_user_id_list @"curUserIdList"
#define IMMsgData_attach_data @"attachData"
@interface IMMsgData : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromUserId_:1;
  BOOL hasToSessionId_:1;
  BOOL hasMsgId_:1;
  BOOL hasMsgData_:1;
  BOOL hasAttachData_:1;
  BOOL hasCreateTime_:1;
  BOOL hasSenderLastetUpdated_:1;
  BOOL hasMsgType_:1;
  UInt64 fromUserId;
  UInt64 toSessionId;
  UInt64 msgId;
  NSData* msgData;
  NSData* attachData;
  UInt32 createTime;
  UInt32 senderLastetUpdated;
  MsgType msgType;
  PBAppendableArray * curUserIdListArray;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToSessionId;
- (BOOL) hasMsgId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
- (BOOL) hasSenderLastetUpdated;
- (BOOL) hasAttachData;
@property (readonly) UInt64 fromUserId;
@property (readonly) UInt64 toSessionId;
@property (readonly) UInt64 msgId;
@property (readonly) UInt32 createTime;
@property (readonly) MsgType msgType;
@property (readonly, strong) NSData* msgData;
@property (readonly) UInt32 senderLastetUpdated;
@property (readonly, strong) PBArray * curUserIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMMsgDataBuilder*) builder;
+ (IMMsgDataBuilder*) builder;
+ (IMMsgDataBuilder*) builderWithPrototype:(IMMsgData*) prototype;
- (IMMsgDataBuilder*) toBuilder;

+ (IMMsgData*) parseFromData:(NSData*) data;
+ (IMMsgData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgData*) parseFromInputStream:(NSInputStream*) input;
+ (IMMsgData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMMsgData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMMsgDataBuilder : PBGeneratedMessageBuilder {
@private
  IMMsgData* resultImmsgData;
}

- (IMMsgData*) defaultInstance;

- (IMMsgDataBuilder*) clear;
- (IMMsgDataBuilder*) clone;

- (IMMsgData*) build;
- (IMMsgData*) buildPartial;

- (IMMsgDataBuilder*) mergeFrom:(IMMsgData*) other;
- (IMMsgDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMMsgDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt64) fromUserId;
- (IMMsgDataBuilder*) setFromUserId:(UInt64) value;
- (IMMsgDataBuilder*) clearFromUserId;

- (BOOL) hasToSessionId;
- (UInt64) toSessionId;
- (IMMsgDataBuilder*) setToSessionId:(UInt64) value;
- (IMMsgDataBuilder*) clearToSessionId;

- (BOOL) hasMsgId;
- (UInt64) msgId;
- (IMMsgDataBuilder*) setMsgId:(UInt64) value;
- (IMMsgDataBuilder*) clearMsgId;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (IMMsgDataBuilder*) setCreateTime:(UInt32) value;
- (IMMsgDataBuilder*) clearCreateTime;

- (BOOL) hasMsgType;
- (MsgType) msgType;
- (IMMsgDataBuilder*) setMsgType:(MsgType) value;
- (IMMsgDataBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (IMMsgDataBuilder*) setMsgData:(NSData*) value;
- (IMMsgDataBuilder*) clearMsgData;

- (BOOL) hasSenderLastetUpdated;
- (UInt32) senderLastetUpdated;
- (IMMsgDataBuilder*) setSenderLastetUpdated:(UInt32) value;
- (IMMsgDataBuilder*) clearSenderLastetUpdated;

- (PBAppendableArray *)curUserIdList;
- (UInt64)curUserIdListAtIndex:(NSUInteger)index;
- (IMMsgDataBuilder *)addCurUserIdList:(UInt64)value;
- (IMMsgDataBuilder *)setCurUserIdListArray:(NSArray *)array;
- (IMMsgDataBuilder *)setCurUserIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMMsgDataBuilder *)clearCurUserIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMMsgDataBuilder*) setAttachData:(NSData*) value;
- (IMMsgDataBuilder*) clearAttachData;
@end

#define IMMsgDataAck_user_id @"userId"
#define IMMsgDataAck_session_id @"sessionId"
#define IMMsgDataAck_msg_id @"msgId"
#define IMMsgDataAck_session_type @"sessionType"
@interface IMMsgDataAck : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasMsgId_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 msgId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionId;
- (BOOL) hasMsgId;
- (BOOL) hasSessionType;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 msgId;
@property (readonly) SessionType sessionType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMMsgDataAckBuilder*) builder;
+ (IMMsgDataAckBuilder*) builder;
+ (IMMsgDataAckBuilder*) builderWithPrototype:(IMMsgDataAck*) prototype;
- (IMMsgDataAckBuilder*) toBuilder;

+ (IMMsgDataAck*) parseFromData:(NSData*) data;
+ (IMMsgDataAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataAck*) parseFromInputStream:(NSInputStream*) input;
+ (IMMsgDataAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMMsgDataAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMMsgDataAckBuilder : PBGeneratedMessageBuilder {
@private
  IMMsgDataAck* resultImmsgDataAck;
}

- (IMMsgDataAck*) defaultInstance;

- (IMMsgDataAckBuilder*) clear;
- (IMMsgDataAckBuilder*) clone;

- (IMMsgDataAck*) build;
- (IMMsgDataAck*) buildPartial;

- (IMMsgDataAckBuilder*) mergeFrom:(IMMsgDataAck*) other;
- (IMMsgDataAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMMsgDataAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMMsgDataAckBuilder*) setUserId:(UInt64) value;
- (IMMsgDataAckBuilder*) clearUserId;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMMsgDataAckBuilder*) setSessionId:(UInt64) value;
- (IMMsgDataAckBuilder*) clearSessionId;

- (BOOL) hasMsgId;
- (UInt64) msgId;
- (IMMsgDataAckBuilder*) setMsgId:(UInt64) value;
- (IMMsgDataAckBuilder*) clearMsgId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMMsgDataAckBuilder*) setSessionType:(SessionType) value;
- (IMMsgDataAckBuilder*) clearSessionType;
@end

#define IMMsgDataReadAck_user_id @"userId"
#define IMMsgDataReadAck_session_id @"sessionId"
#define IMMsgDataReadAck_msg_id @"msgId"
#define IMMsgDataReadAck_session_type @"sessionType"
@interface IMMsgDataReadAck : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasMsgId_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 msgId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionId;
- (BOOL) hasMsgId;
- (BOOL) hasSessionType;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 msgId;
@property (readonly) SessionType sessionType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMMsgDataReadAckBuilder*) builder;
+ (IMMsgDataReadAckBuilder*) builder;
+ (IMMsgDataReadAckBuilder*) builderWithPrototype:(IMMsgDataReadAck*) prototype;
- (IMMsgDataReadAckBuilder*) toBuilder;

+ (IMMsgDataReadAck*) parseFromData:(NSData*) data;
+ (IMMsgDataReadAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataReadAck*) parseFromInputStream:(NSInputStream*) input;
+ (IMMsgDataReadAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMMsgDataReadAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMMsgDataReadAckBuilder : PBGeneratedMessageBuilder {
@private
  IMMsgDataReadAck* resultImmsgDataReadAck;
}

- (IMMsgDataReadAck*) defaultInstance;

- (IMMsgDataReadAckBuilder*) clear;
- (IMMsgDataReadAckBuilder*) clone;

- (IMMsgDataReadAck*) build;
- (IMMsgDataReadAck*) buildPartial;

- (IMMsgDataReadAckBuilder*) mergeFrom:(IMMsgDataReadAck*) other;
- (IMMsgDataReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMMsgDataReadAckBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMMsgDataReadAckBuilder*) setUserId:(UInt64) value;
- (IMMsgDataReadAckBuilder*) clearUserId;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMMsgDataReadAckBuilder*) setSessionId:(UInt64) value;
- (IMMsgDataReadAckBuilder*) clearSessionId;

- (BOOL) hasMsgId;
- (UInt64) msgId;
- (IMMsgDataReadAckBuilder*) setMsgId:(UInt64) value;
- (IMMsgDataReadAckBuilder*) clearMsgId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMMsgDataReadAckBuilder*) setSessionType:(SessionType) value;
- (IMMsgDataReadAckBuilder*) clearSessionType;
@end

#define IMMsgDataReadNotify_user_id @"userId"
#define IMMsgDataReadNotify_session_id @"sessionId"
#define IMMsgDataReadNotify_msg_id @"msgId"
#define IMMsgDataReadNotify_session_type @"sessionType"
@interface IMMsgDataReadNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasMsgId_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 msgId;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionId;
- (BOOL) hasMsgId;
- (BOOL) hasSessionType;
@property (readonly) UInt64 userId;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 msgId;
@property (readonly) SessionType sessionType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMMsgDataReadNotifyBuilder*) builder;
+ (IMMsgDataReadNotifyBuilder*) builder;
+ (IMMsgDataReadNotifyBuilder*) builderWithPrototype:(IMMsgDataReadNotify*) prototype;
- (IMMsgDataReadNotifyBuilder*) toBuilder;

+ (IMMsgDataReadNotify*) parseFromData:(NSData*) data;
+ (IMMsgDataReadNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataReadNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMMsgDataReadNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMMsgDataReadNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMMsgDataReadNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMMsgDataReadNotifyBuilder : PBGeneratedMessageBuilder {
@private
  IMMsgDataReadNotify* resultImmsgDataReadNotify;
}

- (IMMsgDataReadNotify*) defaultInstance;

- (IMMsgDataReadNotifyBuilder*) clear;
- (IMMsgDataReadNotifyBuilder*) clone;

- (IMMsgDataReadNotify*) build;
- (IMMsgDataReadNotify*) buildPartial;

- (IMMsgDataReadNotifyBuilder*) mergeFrom:(IMMsgDataReadNotify*) other;
- (IMMsgDataReadNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMMsgDataReadNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMMsgDataReadNotifyBuilder*) setUserId:(UInt64) value;
- (IMMsgDataReadNotifyBuilder*) clearUserId;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMMsgDataReadNotifyBuilder*) setSessionId:(UInt64) value;
- (IMMsgDataReadNotifyBuilder*) clearSessionId;

- (BOOL) hasMsgId;
- (UInt64) msgId;
- (IMMsgDataReadNotifyBuilder*) setMsgId:(UInt64) value;
- (IMMsgDataReadNotifyBuilder*) clearMsgId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMMsgDataReadNotifyBuilder*) setSessionType:(SessionType) value;
- (IMMsgDataReadNotifyBuilder*) clearSessionType;
@end

@interface IMClientTimeReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMClientTimeReqBuilder*) builder;
+ (IMClientTimeReqBuilder*) builder;
+ (IMClientTimeReqBuilder*) builderWithPrototype:(IMClientTimeReq*) prototype;
- (IMClientTimeReqBuilder*) toBuilder;

+ (IMClientTimeReq*) parseFromData:(NSData*) data;
+ (IMClientTimeReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMClientTimeReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMClientTimeReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMClientTimeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMClientTimeReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMClientTimeReqBuilder : PBGeneratedMessageBuilder {
@private
  IMClientTimeReq* resultImclientTimeReq;
}

- (IMClientTimeReq*) defaultInstance;

- (IMClientTimeReqBuilder*) clear;
- (IMClientTimeReqBuilder*) clone;

- (IMClientTimeReq*) build;
- (IMClientTimeReq*) buildPartial;

- (IMClientTimeReqBuilder*) mergeFrom:(IMClientTimeReq*) other;
- (IMClientTimeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMClientTimeReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define IMClientTimeRsp_server_time @"serverTime"
@interface IMClientTimeRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasServerTime_:1;
  UInt32 serverTime;
}
- (BOOL) hasServerTime;
@property (readonly) UInt32 serverTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMClientTimeRspBuilder*) builder;
+ (IMClientTimeRspBuilder*) builder;
+ (IMClientTimeRspBuilder*) builderWithPrototype:(IMClientTimeRsp*) prototype;
- (IMClientTimeRspBuilder*) toBuilder;

+ (IMClientTimeRsp*) parseFromData:(NSData*) data;
+ (IMClientTimeRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMClientTimeRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMClientTimeRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMClientTimeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMClientTimeRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMClientTimeRspBuilder : PBGeneratedMessageBuilder {
@private
  IMClientTimeRsp* resultImclientTimeRsp;
}

- (IMClientTimeRsp*) defaultInstance;

- (IMClientTimeRspBuilder*) clear;
- (IMClientTimeRspBuilder*) clone;

- (IMClientTimeRsp*) build;
- (IMClientTimeRsp*) buildPartial;

- (IMClientTimeRspBuilder*) mergeFrom:(IMClientTimeRsp*) other;
- (IMClientTimeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMClientTimeRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasServerTime;
- (UInt32) serverTime;
- (IMClientTimeRspBuilder*) setServerTime:(UInt32) value;
- (IMClientTimeRspBuilder*) clearServerTime;
@end

#define IMUnreadMsgCntReq_user_id @"userId"
#define IMUnreadMsgCntReq_attach_data @"attachData"
@interface IMUnreadMsgCntReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  UInt64 userId;
  NSData* attachData;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUnreadMsgCntReqBuilder*) builder;
+ (IMUnreadMsgCntReqBuilder*) builder;
+ (IMUnreadMsgCntReqBuilder*) builderWithPrototype:(IMUnreadMsgCntReq*) prototype;
- (IMUnreadMsgCntReqBuilder*) toBuilder;

+ (IMUnreadMsgCntReq*) parseFromData:(NSData*) data;
+ (IMUnreadMsgCntReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUnreadMsgCntReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMUnreadMsgCntReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUnreadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUnreadMsgCntReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUnreadMsgCntReqBuilder : PBGeneratedMessageBuilder {
@private
  IMUnreadMsgCntReq* resultImunreadMsgCntReq;
}

- (IMUnreadMsgCntReq*) defaultInstance;

- (IMUnreadMsgCntReqBuilder*) clear;
- (IMUnreadMsgCntReqBuilder*) clone;

- (IMUnreadMsgCntReq*) build;
- (IMUnreadMsgCntReq*) buildPartial;

- (IMUnreadMsgCntReqBuilder*) mergeFrom:(IMUnreadMsgCntReq*) other;
- (IMUnreadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUnreadMsgCntReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMUnreadMsgCntReqBuilder*) setUserId:(UInt64) value;
- (IMUnreadMsgCntReqBuilder*) clearUserId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUnreadMsgCntReqBuilder*) setAttachData:(NSData*) value;
- (IMUnreadMsgCntReqBuilder*) clearAttachData;
@end

#define IMUnreadMsgCntRsp_user_id @"userId"
#define IMUnreadMsgCntRsp_total_cnt @"totalCnt"
#define IMUnreadMsgCntRsp_unreadinfo_list @"unreadinfoList"
#define IMUnreadMsgCntRsp_attach_data @"attachData"
@interface IMUnreadMsgCntRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAttachData_:1;
  BOOL hasTotalCnt_:1;
  UInt64 userId;
  NSData* attachData;
  UInt32 totalCnt;
  NSMutableArray * unreadinfoListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasTotalCnt;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) UInt32 totalCnt;
@property (readonly, strong) NSArray * unreadinfoList;
@property (readonly, strong) NSData* attachData;
- (UnreadInfo*)unreadinfoListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMUnreadMsgCntRspBuilder*) builder;
+ (IMUnreadMsgCntRspBuilder*) builder;
+ (IMUnreadMsgCntRspBuilder*) builderWithPrototype:(IMUnreadMsgCntRsp*) prototype;
- (IMUnreadMsgCntRspBuilder*) toBuilder;

+ (IMUnreadMsgCntRsp*) parseFromData:(NSData*) data;
+ (IMUnreadMsgCntRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUnreadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMUnreadMsgCntRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMUnreadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMUnreadMsgCntRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMUnreadMsgCntRspBuilder : PBGeneratedMessageBuilder {
@private
  IMUnreadMsgCntRsp* resultImunreadMsgCntRsp;
}

- (IMUnreadMsgCntRsp*) defaultInstance;

- (IMUnreadMsgCntRspBuilder*) clear;
- (IMUnreadMsgCntRspBuilder*) clone;

- (IMUnreadMsgCntRsp*) build;
- (IMUnreadMsgCntRsp*) buildPartial;

- (IMUnreadMsgCntRspBuilder*) mergeFrom:(IMUnreadMsgCntRsp*) other;
- (IMUnreadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMUnreadMsgCntRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMUnreadMsgCntRspBuilder*) setUserId:(UInt64) value;
- (IMUnreadMsgCntRspBuilder*) clearUserId;

- (BOOL) hasTotalCnt;
- (UInt32) totalCnt;
- (IMUnreadMsgCntRspBuilder*) setTotalCnt:(UInt32) value;
- (IMUnreadMsgCntRspBuilder*) clearTotalCnt;

- (NSMutableArray *)unreadinfoList;
- (UnreadInfo*)unreadinfoListAtIndex:(NSUInteger)index;
- (IMUnreadMsgCntRspBuilder *)addUnreadinfoList:(UnreadInfo*)value;
- (IMUnreadMsgCntRspBuilder *)setUnreadinfoListArray:(NSArray *)array;
- (IMUnreadMsgCntRspBuilder *)clearUnreadinfoList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMUnreadMsgCntRspBuilder*) setAttachData:(NSData*) value;
- (IMUnreadMsgCntRspBuilder*) clearAttachData;
@end

#define IMGetMsgListReq_user_id @"userId"
#define IMGetMsgListReq_session_type @"sessionType"
#define IMGetMsgListReq_session_id @"sessionId"
#define IMGetMsgListReq_msg_id_begin @"msgIdBegin"
#define IMGetMsgListReq_msg_cnt @"msgCnt"
#define IMGetMsgListReq_attach_data @"attachData"
@interface IMGetMsgListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasMsgIdBegin_:1;
  BOOL hasAttachData_:1;
  BOOL hasMsgCnt_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 msgIdBegin;
  NSData* attachData;
  UInt32 msgCnt;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasMsgIdBegin;
- (BOOL) hasMsgCnt;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 msgIdBegin;
@property (readonly) UInt32 msgCnt;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetMsgListReqBuilder*) builder;
+ (IMGetMsgListReqBuilder*) builder;
+ (IMGetMsgListReqBuilder*) builderWithPrototype:(IMGetMsgListReq*) prototype;
- (IMGetMsgListReqBuilder*) toBuilder;

+ (IMGetMsgListReq*) parseFromData:(NSData*) data;
+ (IMGetMsgListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgListReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetMsgListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetMsgListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetMsgListReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGetMsgListReq* resultImgetMsgListReq;
}

- (IMGetMsgListReq*) defaultInstance;

- (IMGetMsgListReqBuilder*) clear;
- (IMGetMsgListReqBuilder*) clone;

- (IMGetMsgListReq*) build;
- (IMGetMsgListReq*) buildPartial;

- (IMGetMsgListReqBuilder*) mergeFrom:(IMGetMsgListReq*) other;
- (IMGetMsgListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetMsgListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetMsgListReqBuilder*) setUserId:(UInt64) value;
- (IMGetMsgListReqBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetMsgListReqBuilder*) setSessionType:(SessionType) value;
- (IMGetMsgListReqBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetMsgListReqBuilder*) setSessionId:(UInt64) value;
- (IMGetMsgListReqBuilder*) clearSessionId;

- (BOOL) hasMsgIdBegin;
- (UInt64) msgIdBegin;
- (IMGetMsgListReqBuilder*) setMsgIdBegin:(UInt64) value;
- (IMGetMsgListReqBuilder*) clearMsgIdBegin;

- (BOOL) hasMsgCnt;
- (UInt32) msgCnt;
- (IMGetMsgListReqBuilder*) setMsgCnt:(UInt32) value;
- (IMGetMsgListReqBuilder*) clearMsgCnt;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetMsgListReqBuilder*) setAttachData:(NSData*) value;
- (IMGetMsgListReqBuilder*) clearAttachData;
@end

#define IMGetMsgListRsp_user_id @"userId"
#define IMGetMsgListRsp_session_type @"sessionType"
#define IMGetMsgListRsp_session_id @"sessionId"
#define IMGetMsgListRsp_msg_id_begin @"msgIdBegin"
#define IMGetMsgListRsp_msg_list @"msgList"
#define IMGetMsgListRsp_attach_data @"attachData"
@interface IMGetMsgListRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasMsgIdBegin_:1;
  BOOL hasAttachData_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 msgIdBegin;
  NSData* attachData;
  SessionType sessionType;
  NSMutableArray * msgListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasMsgIdBegin;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 msgIdBegin;
@property (readonly, strong) NSArray * msgList;
@property (readonly, strong) NSData* attachData;
- (MsgInfo*)msgListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetMsgListRspBuilder*) builder;
+ (IMGetMsgListRspBuilder*) builder;
+ (IMGetMsgListRspBuilder*) builderWithPrototype:(IMGetMsgListRsp*) prototype;
- (IMGetMsgListRspBuilder*) toBuilder;

+ (IMGetMsgListRsp*) parseFromData:(NSData*) data;
+ (IMGetMsgListRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgListRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetMsgListRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetMsgListRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetMsgListRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGetMsgListRsp* resultImgetMsgListRsp;
}

- (IMGetMsgListRsp*) defaultInstance;

- (IMGetMsgListRspBuilder*) clear;
- (IMGetMsgListRspBuilder*) clone;

- (IMGetMsgListRsp*) build;
- (IMGetMsgListRsp*) buildPartial;

- (IMGetMsgListRspBuilder*) mergeFrom:(IMGetMsgListRsp*) other;
- (IMGetMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetMsgListRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetMsgListRspBuilder*) setUserId:(UInt64) value;
- (IMGetMsgListRspBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetMsgListRspBuilder*) setSessionType:(SessionType) value;
- (IMGetMsgListRspBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetMsgListRspBuilder*) setSessionId:(UInt64) value;
- (IMGetMsgListRspBuilder*) clearSessionId;

- (BOOL) hasMsgIdBegin;
- (UInt64) msgIdBegin;
- (IMGetMsgListRspBuilder*) setMsgIdBegin:(UInt64) value;
- (IMGetMsgListRspBuilder*) clearMsgIdBegin;

- (NSMutableArray *)msgList;
- (MsgInfo*)msgListAtIndex:(NSUInteger)index;
- (IMGetMsgListRspBuilder *)addMsgList:(MsgInfo*)value;
- (IMGetMsgListRspBuilder *)setMsgListArray:(NSArray *)array;
- (IMGetMsgListRspBuilder *)clearMsgList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetMsgListRspBuilder*) setAttachData:(NSData*) value;
- (IMGetMsgListRspBuilder*) clearAttachData;
@end

#define IMGetLatestMsgIdReq_user_id @"userId"
#define IMGetLatestMsgIdReq_session_type @"sessionType"
#define IMGetLatestMsgIdReq_session_id @"sessionId"
#define IMGetLatestMsgIdReq_attach_data @"attachData"
@interface IMGetLatestMsgIdReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasAttachData_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  NSData* attachData;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetLatestMsgIdReqBuilder*) builder;
+ (IMGetLatestMsgIdReqBuilder*) builder;
+ (IMGetLatestMsgIdReqBuilder*) builderWithPrototype:(IMGetLatestMsgIdReq*) prototype;
- (IMGetLatestMsgIdReqBuilder*) toBuilder;

+ (IMGetLatestMsgIdReq*) parseFromData:(NSData*) data;
+ (IMGetLatestMsgIdReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetLatestMsgIdReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetLatestMsgIdReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetLatestMsgIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetLatestMsgIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetLatestMsgIdReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGetLatestMsgIdReq* resultImgetLatestMsgIdReq;
}

- (IMGetLatestMsgIdReq*) defaultInstance;

- (IMGetLatestMsgIdReqBuilder*) clear;
- (IMGetLatestMsgIdReqBuilder*) clone;

- (IMGetLatestMsgIdReq*) build;
- (IMGetLatestMsgIdReq*) buildPartial;

- (IMGetLatestMsgIdReqBuilder*) mergeFrom:(IMGetLatestMsgIdReq*) other;
- (IMGetLatestMsgIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetLatestMsgIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetLatestMsgIdReqBuilder*) setUserId:(UInt64) value;
- (IMGetLatestMsgIdReqBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetLatestMsgIdReqBuilder*) setSessionType:(SessionType) value;
- (IMGetLatestMsgIdReqBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetLatestMsgIdReqBuilder*) setSessionId:(UInt64) value;
- (IMGetLatestMsgIdReqBuilder*) clearSessionId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetLatestMsgIdReqBuilder*) setAttachData:(NSData*) value;
- (IMGetLatestMsgIdReqBuilder*) clearAttachData;
@end

#define IMGetLatestMsgIdRsp_user_id @"userId"
#define IMGetLatestMsgIdRsp_session_type @"sessionType"
#define IMGetLatestMsgIdRsp_session_id @"sessionId"
#define IMGetLatestMsgIdRsp_latest_msg_id @"latestMsgId"
#define IMGetLatestMsgIdRsp_attach_data @"attachData"
@interface IMGetLatestMsgIdRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasLatestMsgId_:1;
  BOOL hasAttachData_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  UInt64 latestMsgId;
  NSData* attachData;
  SessionType sessionType;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasLatestMsgId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly) UInt64 latestMsgId;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetLatestMsgIdRspBuilder*) builder;
+ (IMGetLatestMsgIdRspBuilder*) builder;
+ (IMGetLatestMsgIdRspBuilder*) builderWithPrototype:(IMGetLatestMsgIdRsp*) prototype;
- (IMGetLatestMsgIdRspBuilder*) toBuilder;

+ (IMGetLatestMsgIdRsp*) parseFromData:(NSData*) data;
+ (IMGetLatestMsgIdRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetLatestMsgIdRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetLatestMsgIdRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetLatestMsgIdRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetLatestMsgIdRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetLatestMsgIdRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGetLatestMsgIdRsp* resultImgetLatestMsgIdRsp;
}

- (IMGetLatestMsgIdRsp*) defaultInstance;

- (IMGetLatestMsgIdRspBuilder*) clear;
- (IMGetLatestMsgIdRspBuilder*) clone;

- (IMGetLatestMsgIdRsp*) build;
- (IMGetLatestMsgIdRsp*) buildPartial;

- (IMGetLatestMsgIdRspBuilder*) mergeFrom:(IMGetLatestMsgIdRsp*) other;
- (IMGetLatestMsgIdRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetLatestMsgIdRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetLatestMsgIdRspBuilder*) setUserId:(UInt64) value;
- (IMGetLatestMsgIdRspBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetLatestMsgIdRspBuilder*) setSessionType:(SessionType) value;
- (IMGetLatestMsgIdRspBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetLatestMsgIdRspBuilder*) setSessionId:(UInt64) value;
- (IMGetLatestMsgIdRspBuilder*) clearSessionId;

- (BOOL) hasLatestMsgId;
- (UInt64) latestMsgId;
- (IMGetLatestMsgIdRspBuilder*) setLatestMsgId:(UInt64) value;
- (IMGetLatestMsgIdRspBuilder*) clearLatestMsgId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetLatestMsgIdRspBuilder*) setAttachData:(NSData*) value;
- (IMGetLatestMsgIdRspBuilder*) clearAttachData;
@end

#define IMGetMsgByIdReq_user_id @"userId"
#define IMGetMsgByIdReq_session_type @"sessionType"
#define IMGetMsgByIdReq_session_id @"sessionId"
#define IMGetMsgByIdReq_msg_id_list @"msgIdList"
#define IMGetMsgByIdReq_attach_data @"attachData"
@interface IMGetMsgByIdReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasAttachData_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  NSData* attachData;
  SessionType sessionType;
  PBAppendableArray * msgIdListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly, strong) PBArray * msgIdList;
@property (readonly, strong) NSData* attachData;
- (UInt64)msgIdListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetMsgByIdReqBuilder*) builder;
+ (IMGetMsgByIdReqBuilder*) builder;
+ (IMGetMsgByIdReqBuilder*) builderWithPrototype:(IMGetMsgByIdReq*) prototype;
- (IMGetMsgByIdReqBuilder*) toBuilder;

+ (IMGetMsgByIdReq*) parseFromData:(NSData*) data;
+ (IMGetMsgByIdReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgByIdReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetMsgByIdReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgByIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetMsgByIdReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetMsgByIdReqBuilder : PBGeneratedMessageBuilder {
@private
  IMGetMsgByIdReq* resultImgetMsgByIdReq;
}

- (IMGetMsgByIdReq*) defaultInstance;

- (IMGetMsgByIdReqBuilder*) clear;
- (IMGetMsgByIdReqBuilder*) clone;

- (IMGetMsgByIdReq*) build;
- (IMGetMsgByIdReq*) buildPartial;

- (IMGetMsgByIdReqBuilder*) mergeFrom:(IMGetMsgByIdReq*) other;
- (IMGetMsgByIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetMsgByIdReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetMsgByIdReqBuilder*) setUserId:(UInt64) value;
- (IMGetMsgByIdReqBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetMsgByIdReqBuilder*) setSessionType:(SessionType) value;
- (IMGetMsgByIdReqBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetMsgByIdReqBuilder*) setSessionId:(UInt64) value;
- (IMGetMsgByIdReqBuilder*) clearSessionId;

- (PBAppendableArray *)msgIdList;
- (UInt64)msgIdListAtIndex:(NSUInteger)index;
- (IMGetMsgByIdReqBuilder *)addMsgIdList:(UInt64)value;
- (IMGetMsgByIdReqBuilder *)setMsgIdListArray:(NSArray *)array;
- (IMGetMsgByIdReqBuilder *)setMsgIdListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMGetMsgByIdReqBuilder *)clearMsgIdList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetMsgByIdReqBuilder*) setAttachData:(NSData*) value;
- (IMGetMsgByIdReqBuilder*) clearAttachData;
@end

#define IMGetMsgByIdRsp_user_id @"userId"
#define IMGetMsgByIdRsp_session_type @"sessionType"
#define IMGetMsgByIdRsp_session_id @"sessionId"
#define IMGetMsgByIdRsp_msg_list @"msgList"
#define IMGetMsgByIdRsp_attach_data @"attachData"
@interface IMGetMsgByIdRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasSessionId_:1;
  BOOL hasAttachData_:1;
  BOOL hasSessionType_:1;
  UInt64 userId;
  UInt64 sessionId;
  NSData* attachData;
  SessionType sessionType;
  NSMutableArray * msgListArray;
}
- (BOOL) hasUserId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionId;
- (BOOL) hasAttachData;
@property (readonly) UInt64 userId;
@property (readonly) SessionType sessionType;
@property (readonly) UInt64 sessionId;
@property (readonly, strong) NSArray * msgList;
@property (readonly, strong) NSData* attachData;
- (MsgInfo*)msgListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMGetMsgByIdRspBuilder*) builder;
+ (IMGetMsgByIdRspBuilder*) builder;
+ (IMGetMsgByIdRspBuilder*) builderWithPrototype:(IMGetMsgByIdRsp*) prototype;
- (IMGetMsgByIdRspBuilder*) toBuilder;

+ (IMGetMsgByIdRsp*) parseFromData:(NSData*) data;
+ (IMGetMsgByIdRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgByIdRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMGetMsgByIdRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMGetMsgByIdRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMGetMsgByIdRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMGetMsgByIdRspBuilder : PBGeneratedMessageBuilder {
@private
  IMGetMsgByIdRsp* resultImgetMsgByIdRsp;
}

- (IMGetMsgByIdRsp*) defaultInstance;

- (IMGetMsgByIdRspBuilder*) clear;
- (IMGetMsgByIdRspBuilder*) clone;

- (IMGetMsgByIdRsp*) build;
- (IMGetMsgByIdRsp*) buildPartial;

- (IMGetMsgByIdRspBuilder*) mergeFrom:(IMGetMsgByIdRsp*) other;
- (IMGetMsgByIdRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMGetMsgByIdRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (UInt64) userId;
- (IMGetMsgByIdRspBuilder*) setUserId:(UInt64) value;
- (IMGetMsgByIdRspBuilder*) clearUserId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (IMGetMsgByIdRspBuilder*) setSessionType:(SessionType) value;
- (IMGetMsgByIdRspBuilder*) clearSessionType;

- (BOOL) hasSessionId;
- (UInt64) sessionId;
- (IMGetMsgByIdRspBuilder*) setSessionId:(UInt64) value;
- (IMGetMsgByIdRspBuilder*) clearSessionId;

- (NSMutableArray *)msgList;
- (MsgInfo*)msgListAtIndex:(NSUInteger)index;
- (IMGetMsgByIdRspBuilder *)addMsgList:(MsgInfo*)value;
- (IMGetMsgByIdRspBuilder *)setMsgListArray:(NSArray *)array;
- (IMGetMsgByIdRspBuilder *)clearMsgList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMGetMsgByIdRspBuilder*) setAttachData:(NSData*) value;
- (IMGetMsgByIdRspBuilder*) clearAttachData;
@end

#define IMSubscribeHttpSendMessageRequest_sb_uuid @"sbUuid"
#define IMSubscribeHttpSendMessageRequest_sb_id @"sbId"
#define IMSubscribeHttpSendMessageRequest_infoid @"infoid"
#define IMSubscribeHttpSendMessageRequest_user_list @"userList"
#define IMSubscribeHttpSendMessageRequest_msg_type @"msgType"
#define IMSubscribeHttpSendMessageRequest_msg_data @"msgData"
#define IMSubscribeHttpSendMessageRequest_group_id @"groupId"
#define IMSubscribeHttpSendMessageRequest_sb_loginid @"sbLoginid"
#define IMSubscribeHttpSendMessageRequest_attach_data @"attachData"
@interface IMSubscribeHttpSendMessageRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSbId_:1;
  BOOL hasSbLoginid_:1;
  BOOL hasSbUuid_:1;
  BOOL hasInfoid_:1;
  BOOL hasGroupId_:1;
  BOOL hasMsgData_:1;
  BOOL hasAttachData_:1;
  BOOL hasMsgType_:1;
  UInt64 sbId;
  UInt64 sbLoginid;
  NSString* sbUuid;
  NSString* infoid;
  NSString* groupId;
  NSData* msgData;
  NSData* attachData;
  MsgType msgType;
  PBAppendableArray * userListArray;
}
- (BOOL) hasSbUuid;
- (BOOL) hasSbId;
- (BOOL) hasInfoid;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
- (BOOL) hasGroupId;
- (BOOL) hasSbLoginid;
- (BOOL) hasAttachData;
@property (readonly, strong) NSString* sbUuid;
@property (readonly) UInt64 sbId;
@property (readonly, strong) NSString* infoid;
@property (readonly, strong) PBArray * userList;
@property (readonly) MsgType msgType;
@property (readonly, strong) NSData* msgData;
@property (readonly, strong) NSString* groupId;
@property (readonly) UInt64 sbLoginid;
@property (readonly, strong) NSData* attachData;
- (UInt64)userListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMSubscribeHttpSendMessageRequestBuilder*) builder;
+ (IMSubscribeHttpSendMessageRequestBuilder*) builder;
+ (IMSubscribeHttpSendMessageRequestBuilder*) builderWithPrototype:(IMSubscribeHttpSendMessageRequest*) prototype;
- (IMSubscribeHttpSendMessageRequestBuilder*) toBuilder;

+ (IMSubscribeHttpSendMessageRequest*) parseFromData:(NSData*) data;
+ (IMSubscribeHttpSendMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSubscribeHttpSendMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (IMSubscribeHttpSendMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSubscribeHttpSendMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMSubscribeHttpSendMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMSubscribeHttpSendMessageRequestBuilder : PBGeneratedMessageBuilder {
@private
  IMSubscribeHttpSendMessageRequest* resultImsubscribeHttpSendMessageRequest;
}

- (IMSubscribeHttpSendMessageRequest*) defaultInstance;

- (IMSubscribeHttpSendMessageRequestBuilder*) clear;
- (IMSubscribeHttpSendMessageRequestBuilder*) clone;

- (IMSubscribeHttpSendMessageRequest*) build;
- (IMSubscribeHttpSendMessageRequest*) buildPartial;

- (IMSubscribeHttpSendMessageRequestBuilder*) mergeFrom:(IMSubscribeHttpSendMessageRequest*) other;
- (IMSubscribeHttpSendMessageRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMSubscribeHttpSendMessageRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSbUuid;
- (NSString*) sbUuid;
- (IMSubscribeHttpSendMessageRequestBuilder*) setSbUuid:(NSString*) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearSbUuid;

- (BOOL) hasSbId;
- (UInt64) sbId;
- (IMSubscribeHttpSendMessageRequestBuilder*) setSbId:(UInt64) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearSbId;

- (BOOL) hasInfoid;
- (NSString*) infoid;
- (IMSubscribeHttpSendMessageRequestBuilder*) setInfoid:(NSString*) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearInfoid;

- (PBAppendableArray *)userList;
- (UInt64)userListAtIndex:(NSUInteger)index;
- (IMSubscribeHttpSendMessageRequestBuilder *)addUserList:(UInt64)value;
- (IMSubscribeHttpSendMessageRequestBuilder *)setUserListArray:(NSArray *)array;
- (IMSubscribeHttpSendMessageRequestBuilder *)setUserListValues:(const UInt64 *)values count:(NSUInteger)count;
- (IMSubscribeHttpSendMessageRequestBuilder *)clearUserList;

- (BOOL) hasMsgType;
- (MsgType) msgType;
- (IMSubscribeHttpSendMessageRequestBuilder*) setMsgType:(MsgType) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (IMSubscribeHttpSendMessageRequestBuilder*) setMsgData:(NSData*) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearMsgData;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (IMSubscribeHttpSendMessageRequestBuilder*) setGroupId:(NSString*) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearGroupId;

- (BOOL) hasSbLoginid;
- (UInt64) sbLoginid;
- (IMSubscribeHttpSendMessageRequestBuilder*) setSbLoginid:(UInt64) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearSbLoginid;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMSubscribeHttpSendMessageRequestBuilder*) setAttachData:(NSData*) value;
- (IMSubscribeHttpSendMessageRequestBuilder*) clearAttachData;
@end

#define IMSubscribeHttpSendMessageRespone_sb_uuid @"sbUuid"
#define IMSubscribeHttpSendMessageRespone_sb_id @"sbId"
#define IMSubscribeHttpSendMessageRespone_sbmsgid_list @"sbmsgidList"
#define IMSubscribeHttpSendMessageRespone_msg_type @"msgType"
#define IMSubscribeHttpSendMessageRespone_msg_data @"msgData"
#define IMSubscribeHttpSendMessageRespone_create_time @"createTime"
#define IMSubscribeHttpSendMessageRespone_attach_data @"attachData"
@interface IMSubscribeHttpSendMessageRespone : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSbId_:1;
  BOOL hasSbUuid_:1;
  BOOL hasMsgData_:1;
  BOOL hasAttachData_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  UInt64 sbId;
  NSString* sbUuid;
  NSData* msgData;
  NSData* attachData;
  UInt32 createTime;
  MsgType msgType;
  NSMutableArray * sbmsgidListArray;
}
- (BOOL) hasSbUuid;
- (BOOL) hasSbId;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
- (BOOL) hasCreateTime;
- (BOOL) hasAttachData;
@property (readonly, strong) NSString* sbUuid;
@property (readonly) UInt64 sbId;
@property (readonly, strong) NSArray * sbmsgidList;
@property (readonly) MsgType msgType;
@property (readonly, strong) NSData* msgData;
@property (readonly) UInt32 createTime;
@property (readonly, strong) NSData* attachData;
- (SubsribeMsgIdInfo*)sbmsgidListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMSubscribeHttpSendMessageResponeBuilder*) builder;
+ (IMSubscribeHttpSendMessageResponeBuilder*) builder;
+ (IMSubscribeHttpSendMessageResponeBuilder*) builderWithPrototype:(IMSubscribeHttpSendMessageRespone*) prototype;
- (IMSubscribeHttpSendMessageResponeBuilder*) toBuilder;

+ (IMSubscribeHttpSendMessageRespone*) parseFromData:(NSData*) data;
+ (IMSubscribeHttpSendMessageRespone*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSubscribeHttpSendMessageRespone*) parseFromInputStream:(NSInputStream*) input;
+ (IMSubscribeHttpSendMessageRespone*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSubscribeHttpSendMessageRespone*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMSubscribeHttpSendMessageRespone*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMSubscribeHttpSendMessageResponeBuilder : PBGeneratedMessageBuilder {
@private
  IMSubscribeHttpSendMessageRespone* resultImsubscribeHttpSendMessageRespone;
}

- (IMSubscribeHttpSendMessageRespone*) defaultInstance;

- (IMSubscribeHttpSendMessageResponeBuilder*) clear;
- (IMSubscribeHttpSendMessageResponeBuilder*) clone;

- (IMSubscribeHttpSendMessageRespone*) build;
- (IMSubscribeHttpSendMessageRespone*) buildPartial;

- (IMSubscribeHttpSendMessageResponeBuilder*) mergeFrom:(IMSubscribeHttpSendMessageRespone*) other;
- (IMSubscribeHttpSendMessageResponeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMSubscribeHttpSendMessageResponeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSbUuid;
- (NSString*) sbUuid;
- (IMSubscribeHttpSendMessageResponeBuilder*) setSbUuid:(NSString*) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearSbUuid;

- (BOOL) hasSbId;
- (UInt64) sbId;
- (IMSubscribeHttpSendMessageResponeBuilder*) setSbId:(UInt64) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearSbId;

- (NSMutableArray *)sbmsgidList;
- (SubsribeMsgIdInfo*)sbmsgidListAtIndex:(NSUInteger)index;
- (IMSubscribeHttpSendMessageResponeBuilder *)addSbmsgidList:(SubsribeMsgIdInfo*)value;
- (IMSubscribeHttpSendMessageResponeBuilder *)setSbmsgidListArray:(NSArray *)array;
- (IMSubscribeHttpSendMessageResponeBuilder *)clearSbmsgidList;

- (BOOL) hasMsgType;
- (MsgType) msgType;
- (IMSubscribeHttpSendMessageResponeBuilder*) setMsgType:(MsgType) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (IMSubscribeHttpSendMessageResponeBuilder*) setMsgData:(NSData*) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearMsgData;

- (BOOL) hasCreateTime;
- (UInt32) createTime;
- (IMSubscribeHttpSendMessageResponeBuilder*) setCreateTime:(UInt32) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearCreateTime;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMSubscribeHttpSendMessageResponeBuilder*) setAttachData:(NSData*) value;
- (IMSubscribeHttpSendMessageResponeBuilder*) clearAttachData;
@end


// @@protoc_insertion_point(global_scope)
